version: "3"

networks:
  ouijatv:
    driver: bridge

services:
  app:
    container_name: ouijatv-app
    image: ouijatv/app:latest
    environment:
      PUBLIC_WS_URL: ws://ouija.tv:8000
      NODE_ENV: prod
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - /app
    networks:
      - ouijatv
    depends_on:
      - backend

  backend:
    container_name: ouijatv-backend
    image: ouijatv/backend:latest
    build:
      context: ./python
      dockerfile: .docker/Dockerfile
    restart: always
    volumes:
      - ./python:/app
    networks:
      - ouijatv
