version: "3"

networks:
  ouijatv:
    driver: bridge

services:
  app:
    container_name: ouijatv-app
    image: ouijatv/app:latest
    environment:
      PUBLIC_WS_URL: ws://ouija.tv:8000
      PUBLIC_URL: http://ouija.tv:8000
      NODE_ENV: prod
    build:
      context: ./svelte
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - ./svelte:/app
    networks:
      - ouijatv
    depends_on:
      - backend

  backend:
    container_name: ouijatv-backend
    image: ouijatv/backend:latest
    build:
      context: ./python
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./python:/app
    networks:
      - ouijatv

  chatbot:
    container_name: ouijatv-chatbot
    image: ouijatv/chatbot:latest
    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./chatbot:/app
    networks:
      - ouijatv