version: "3.9"

services:
  app:
    image: ouijatv/app
    build: .
    restart: on-failure
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
